### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by tbergen1** [JawzNETA/sql-scratch-capstone-turn-in#1]
### Criteria 1: Report
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: Your slides are well done.  They are clean and display all of the relevant data in a nice format.  I really like how you described the questions to which you were seeking answers.  I also thought your inclusion of the queries was a nice touch.  You also displayed a great understanding of the actual user journey through the website and seamlessly combined your explanations of this with the underlying data you used to analyze the attribution. Lastly, you inclusion of the graphs at the end gave some nice contrast to your slides and gave a great way to visualize the data.  Awesome job!

### Criteria 2: Query Accuracy
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: All queries accurately retrieve the data intended.  Great job!

### Criteria 3: Query Formatting
* **Score Level**: 3/4 (Exceeds Expectations)
* *Comment(s)*: Queries adhere to most of the rules of the style guide.  There are some indentation issues such as having some column names indented more so than others in your SELECT statements.  Indentation is very important, especially in complex queries, so making sure everything is in line should be paid great attention.  Other than that, good job here!

### Criteria 4: Understanding underlying concepts and terminology
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: Your report demonstrated an understanding of the concepts of attribution.  You provided good insight into what attribution analysis is used for as well as what business insights can be gleaned from its application.  You also gave good advice to the company regarding what course it should take when reinvesting.  Great job!

### Overall Score: 15/16
Overall, you did a great job with this.  You demonstrated clear understanding of the material and developed a good looking, clean report on your findings.  All of your conclusions were supported with evidence coming from well-formatted, accurate queries.  Keep up the good work!

**Comment by JawzNETA** [comment]
Thanks so much!
